### ISSUE TITLE
Gone from npm registry

### ISSUE THREAD

**Issue by oskarer** [nikku/svelte-loader#1]
Noticed that it's gone from npm registry; https://www.npmjs.com/package/@nikku/svelte-loader. Any reason for this?

Was able to get it working anyway by adding;
 "svelte-loader": "git+https://github.com/nikku/svelte-loader",

**Comment by nikku** [comment]
Yes, sorry for that. Publishing the stuff as a user local package was a bad Idea.

I am still hoping that the guys over at [sveltejs/svelte-loader](https://github.com/sveltejs/svelte-loader) implement a loader _or_ accept my loader as a contribution. If the stuff works for you, help me and make some noise at https://github.com/sveltejs/svelte-loader/issues/1.

Would be cool to get an official svelte loader for webpack, soon!

**Comment by nikku** [comment]
For the moment, installing via 

```
"svelte-loader": "git+https://github.com/nikku/svelte-loader",
```

looks like a valid workaround to me.

**Comment by oskarer** [comment]
Thanks! I read the comment about this being moved over to sveltejs organization. Great stuff :)
