### ISSUE TITLE
Transfer to sveltejs organisation

### ISSUE THREAD

**Issue by Rich-Harris** [nikku/svelte-loader#2]
As discussed on https://github.com/sveltejs/svelte-loader/issues/1 – if you're able to transfer this to the sveltejs org, we can get this released and added to the list of officially supported integrations. Thanks!

**Comment by nikku** [comment]
Invited you as a contributor to initiate the transfer.

GitHub tells me `You don’t have the permission to create repositories on sveltejs`.

**Comment by nikku** [comment]
Seems like that does not work, too? :tada:

**Comment by Rich-Harris** [comment]
Thanks – yeah, have accepted the invitation but it's not showing me the 'settings' tab. Maybe I need to be made an admin?

**Comment by nikku** [comment]
No option to make you admin. But who cares. I just requested the transfer to you so you can transfer it to the `sveltejs` organization.

Sorry for the hassle.

**Comment by Rich-Harris** [comment]
Cool – I *think* I did it right, at any rate https://github.com/sveltejs/svelte-loader now exists, and you should have admin control over it. Thanks very much!
